### PR TITLE
UI Clean up Step 2

### PR DESCRIPTION
**Pull request by quetool**
**Context:**

Currently Web3ModalFlutter relies heavily on WalletConnectModalFlutter package. We want to change that and completely decouple them both.

Since Web3ModalFlutter is going to be restyled with v3 designs this is a first step towards that direction.

**Changes:**

- UI Clean up

_Note:_ The PR points to an intermediate branch called feat/v3restyle as I will be adding breaking changes and we don’t want to break anything for devs that may be using the package. Once everything is done we will merge the intermediate branch with master

**Final goal:**

- To have a completely independent Web3Modal package with it's own v3 design style

### CODE REVIEW

**Review by 0xAsimetriq — APPROVED** [review]
Do we need to use @1x (even @2x) assets, believe big majority of phones will only benefit from @3x? So maybe that can be default.

**Comment by quetool** [comment]
You are totally right @0xAsimetriq, no need for 1x anymore (old habits die hard 😅 ).

**Comment by ignaciosantise** [comment]
@quetool wdyt of adding the WalletConnect logo as SVG? in the future you'll probably need to change it's color if the user changes the theme color, maybe it's easier if you use an SVG

**Review by ignaciosantise — APPROVED** [review]

**Comment by quetool** [comment]
@ignaciosantise yes, totally, but in order to do that I first need to modify properly the QR Code library, which is a thirty party repository that I already forked.

**Pull request merged**
